name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git pull
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: liuyusheng@1268748608134123
          password: Lys!QAZ1qaz
          logout: false

      - name: Use Skopeo Tools Sync Image to Docker Hub
        run: |
          skopeo copy docker://docker.io/rancher/local-path-provisioner:v0.0.26 docker://registry.cn-hangzhou.aliyuncs.com/images-sysncer/local-path-provisioner:v0.0.26
          skopeo copy docker://docker.io/rancher/mirrored-coredns-coredns:1.10.1 docker://registry.cn-hangzhou.aliyuncs.com/images-sysncer/mirrored-coredns-coredns:1.10.1
          skopeo copy docker://docker.io/rancher/mirrored-metrics-server:v0.7.0 docker://registry.cn-hangzhou.aliyuncs.com/images-sysncer/mirrored-metrics-server:v0.7.0
          skopeo copy docker://docker.io/rancher/klipper-helm:v0.8.3-build20240228 docker://registry.cn-hangzhou.aliyuncs.com/images-sysncer/klipper-helm:v0.8.3-build20240228
