name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git pull
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: liuyusheng@1268748608134123
          password: Lys!QAZ1qaz
          logout: false

      - name: Use Skopeo Tools Sync Image to Docker Hub
        run: |
          skopeo copy docker://docker.io/unguiculus/docker-python3-phantomjs-selenium:v1 docker://registry.cn-hangzhou.aliyuncs.com/images-sysncer/docker-python3-phantomjs-selenium:v1
          skopeo copy docker://docker.io/docker.io/busybox:1.3.2 docker://registry.cn-hangzhou.aliyuncs.com/images-sysncer/busybox:1.3.2
